### ISSUE TITLE
Support for Monitoring child process

### ISSUE THREAD

**Issue by ojhaujjwal** [savetodrive/thekdar#7]
We need to monitor child process
and automatically start a new one when it stops on it own.

We should listen to `exit` event emitted by child process and restart the process immediately.

**Comment by samundrak** [comment]
Currently, once thekdar create new worker and then only task is provided to thekdar as per their limit,
we haven't done things like restart, kill of workers, should be done in future!
Thanks for issue

**Comment by ojhaujjwal** [comment]
I think that manually killing of workers can be a little back down on priority.
but, monitoring child worker processes is very crucial for running on production system.
